---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: authentication-service
    labels:
      app: authentication-service
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: authentication-service
    template:
      metadata:
        labels:
          app: authentication-service
      spec:
        containers:
        - name: authentication-service
          image: docker.pkg.github.com/two-app/authentication-service/authentication-service:0.1.11
          ports:
          - containerPort: 8080
          env:
          - name: SERVER_PORT
            value: "8080"
          - name: SERVER_HOST
            value: "0.0.0.0"
          - name: JDBC_URL
            value: "jdbc:mysql://authentication-service-rds/authentication"
          - name: JDBC_URL_WITHOUT_SCHEMA
            value: "jdbc:mysql://authentication-service-rds"
          - name: JDBC_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: username
          - name: JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 8080
#            initialDelaySeconds: 30 
        imagePullSecrets:
        - name: regcred
  ---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: authentication-service
    name: authentication-service
  spec:
    ports:
    - port: 8080
      name: high
      protocol: TCP
      targetPort: 8080
    - port: 80
      name: low
      protocol: TCP
      targetPort: 8080
    selector:
      app: authentication-service
  ---
  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    name: authentication-service-ingress
  spec:
    rules:
    - http:
        paths:
        - path: /login
          backend:
            serviceName: authentication-service
            servicePort: 80
        - path: /refresh
          backend:
            serviceName: authentication-service
            servicePort: 80
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: authentication-service-rds
  spec:
    type: ClusterIP
    ports:
    - port: 3306
  ---
  apiVersion: v1
  kind: Endpoints
  metadata:
    name: authentication-service-rds
  subsets:
    - addresses:
      - ip: authentication-service.czxkdyhdzjxs.eu-west-1.rds.amazonaws.com
      ports:
      - port: 3306
  ---